### ISSUE TITLE
Tracking issue for Duxbury

### ISSUE THREAD

**Issue by simonw** [natbat/pillarpointstewards#112]
- [x] Manage shift page showing existing confirmed shifts
- [x] Don’t show suggested shift if it’s identical (in terms of start and end time)
- [x] #105
- [x] Add / subtract 15 minutes for shift duration
- [x] #114 
- [x] #116
- [x] #117
- [x] #113
- [x] #122

**Comment by simonw** [comment]
Temporarily dropping the concept of a super low shift that has a different number of people - not enough time to get that working, plus we need to decide how it interacts with the idea of number of people per weekend v.s. per weekday.
